const KEYS={clients:'daan_clients',packages:'daan_packages',payments:'daan_payments',expenses:'daan_expenses',bookings:'daan_bookings'};
const old={packages:'deenAlNoorPackages',payments:'deenAlNoorTransactions',bookings:'deenAlNoorBookings'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function read(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}} function write(k,v){localStorage.setItem(k,JSON.stringify(v))} function id(p){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))} function money(v){return 'KSh '+Number(v||0).toLocaleString('en-KE')} function fmt(v){return v?new Date(v).toLocaleDateString('en-KE'):'—'}
function seed(){if(!read(KEYS.packages).length){let p=read(old.packages);write(KEYS.packages,p.map(x=>({id:x.id||id('pkg'),name:x.name,price:x.price||0,start:x.startDate||'',end:x.endDate||'',hotel:'To be confirmed',transport:'Group coach',services:x.description||'Visa assistance and pilgrimage support'})))}if(!read(KEYS.clients).length)write(KEYS.clients,[]);if(!read(KEYS.payments).length){let t=read(old.payments);write(KEYS.payments,t.filter(x=>x.type==='income').map(x=>({id:id('RCP'),date:x.date,client:x.description?.split(' — ')[0]||'Imported client',amount:x.amount,method:x.method,reference:'Imported'})))}if(!read(KEYS.expenses).length){let t=read(old.payments);write(KEYS.expenses,t.filter(x=>x.type==='expense').map(x=>({id:id('EXP'),date:x.date,description:x.description||'Imported expense',category:'Other',trip:'',amount:x.amount})))}if(!read(KEYS.bookings).length){let b=read(old.bookings);write(KEYS.bookings,b.map(x=>({id:id('BKG'),client:x.name, type:'Inquiry',provider:x.packageName,confirmation:'Pending',start:'',end:'',status:'Pending'})))}}
function flash(m){let f=$('#flash');f.textContent=m;f.style.display='block';setTimeout(()=>f.style.display='none',2400)}
function totals(){let ps=read(KEYS.payments),es=read(KEYS.expenses),income=ps.reduce((a,x)=>a+Number(x.amount||0),0),expense=es.reduce((a,x)=>a+Number(x.amount||0),0);let clients=read(KEYS.clients),out=clients.reduce((a,c)=>a+Math.max(0,Number(c.price||0)-clientPaid(c.name)),0);[['#mIncome',income],['#mExpenses',expense],['#mProfit',income-expense],['#mOutstanding',out],['#rIncome',income],['#rExpenses',expense],['#rProfit',income-expense]].forEach(([s,v])=>$(s).textContent=money(v));}
function clientPaid(name){return read(KEYS.payments).filter(x=>x.client===name).reduce((a,x)=>a+Number(x.amount||0),0)}
function options(){let ps=read(KEYS.packages),cs=read(KEYS.clients);$$('.package-options').forEach(s=>s.innerHTML='<option value="">Select package</option>'+ps.map(x=>`<option>${esc(x.name)}</option>`).join(''));$$('.client-options').forEach(s=>s.innerHTML='<option value="">Select client</option>'+cs.map(x=>`<option>${esc(x.name)}</option>`).join(''))}
function render(){let cs=read(KEYS.clients),ps=read(KEYS.packages),pay=read(KEYS.payments),ex=read(KEYS.expenses),bk=read(KEYS.bookings);$('#clientsTable').innerHTML=cs.length?cs.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.passport)||'—'}</td><td>${esc(c.phone)}</td><td>${esc(c.package)||'—'}</td><td>${money(Math.max(0,Number(c.price||0)-clientPaid(c.name)))}</td><td><div class="actions"><a class="btn outline" href="https://wa.me/${String(c.phone).replace(/\D/g,'')}?text=${encodeURIComponent('Assalamu Alaikum '+c.name+', this is a payment reminder from Deen Al Noor Travels.') }" target="_blank">WhatsApp</a></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No pilgrims registered yet.</td></tr>';
$('#packagesTable').innerHTML=ps.length?ps.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.services||'')}</small></td><td>${fmt(p.start)} – ${fmt(p.end)}</td><td>${money(p.price)}</td><td>${esc(p.hotel)||'—'}</td><td>${esc(p.transport)||'—'}</td><td><button class="btn danger" data-del="packages" data-id="${p.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No packages yet.</td></tr>';
$('#paymentsTable').innerHTML=pay.length?pay.map(p=>`<tr><td><strong>${esc(p.id)}</strong></td><td>${fmt(p.date)}</td><td>${esc(p.client)}</td><td>${esc(p.method)}</td><td>${money(p.amount)}</td><td><button class="btn outline" data-receipt="${p.id}">Receipt</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No payments yet.</td></tr>';
$('#expensesTable').innerHTML=ex.length?ex.map(x=>`<tr><td>${fmt(x.date)}</td><td><span class="badge red">${esc(x.category)}</span></td><td>${esc(x.description)}</td><td>${esc(x.trip)||'—'}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No expenses yet.</td></tr>';
$('#bookingsTable').innerHTML=bk.length?bk.map(x=>`<tr><td>${esc(x.client)}</td><td>${esc(x.type)}</td><td>${esc(x.provider)}</td><td>${fmt(x.start)} – ${fmt(x.end)}</td><td>${esc(x.confirmation)||'—'}</td><td><span class="badge warn">${esc(x.status||'Confirmed')}</span></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No bookings yet.</td></tr>';
let recent=[...pay.map(x=>({...x,type:'Income',description:'Payment — '+x.client})),...ex.map(x=>({...x,type:'Expense'}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,8);$('#recentTx').innerHTML=recent.length?recent.map(x=>`<tr><td>${fmt(x.date)}</td><td>${esc(x.description)}</td><td><span class="badge ${x.type==='Expense'?'red':''}">${x.type}</span></td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No transactions yet.</td></tr>';
let by={};cs.forEach(c=>{let k=c.package||'Unassigned';by[k]??={n:0,r:0,e:0};by[k].n++;by[k].r+=clientPaid(c.name)});$('#tripOverview').innerHTML=Object.keys(by).length?Object.entries(by).map(([k,v])=>`<div><strong>${esc(k)}</strong><div class="bar"><i style="width:${Math.min(100,v.n*10)}%"></i></div><small>${v.n} pilgrim${v.n>1?'s':''} · ${money(v.r)} collected</small></div>`).join(''):'<p class="empty">Add clients to see trip performance.</p>';
$('#profitTable').innerHTML=Object.entries(by).map(([k,v])=>`<tr><td><strong>${esc(k)}</strong></td><td>${v.n}</td><td>${money(v.r)}</td><td>—</td><td>${money(v.r)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No package data yet.</td></tr>';totals();options()}
function formData(f){return Object.fromEntries(new FormData(f).entries())}
function bind(){ $$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));$('#pageTitle').textContent=b.querySelector('span')?.textContent||'Dashboard'});$$('[data-open]').forEach(b=>b.onclick=()=>$( '#'+b.dataset.open).style.display='block');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).style.display='none');$('#clientFormEl').onsubmit=e=>{e.preventDefault();let d=formData(e.target),p=read(KEYS.packages).find(x=>x.name===d.package);write(KEYS.clients,[{...d,id:id('CLI'),price:p?.price||0},...read(KEYS.clients)]);e.target.reset();$('#clientForm').style.display='none';flash('Pilgrim saved');render()};$('#packageFormEl').onsubmit=e=>{e.preventDefault();let d=formData(e.target);write(KEYS.packages,[{...d,id:id('PKG')},...read(KEYS.packages)]);e.target.reset();$('#packageForm').style.display='none';flash('Package created');render()};$('#paymentFormEl').onsubmit=e=>{e.preventDefault();let d=formData(e.target);write(KEYS.payments,[{...d,id:'RCP-'+Date.now().toString().slice(-6),date:new Date().toISOString()},...read(KEYS.payments)]);e.target.reset();$('#paymentForm').style.display='none';flash('Payment saved and receipt issued');render()};$('#expenseFormEl').onsubmit=e=>{e.preventDefault();let d=formData(e.target);write(KEYS.expenses,[{...d,id:id('EXP'),date:new Date().toISOString()},...read(KEYS.expenses)]);e.target.reset();$('#expenseForm').style.display='none';flash('Expense saved');render()};$('#bookingFormEl').onsubmit=e=>{e.preventDefault();let d=formData(e.target);write(KEYS.bookings,[{...d,id:id('BKG'),status:'Confirmed'},...read(KEYS.bookings)]);e.target.reset();$('#bookingForm').style.display='none';flash('Booking saved');render()};document.body.onclick=e=>{let d=e.target.closest('[data-del]');if(d){write(KEYS[d.dataset.del],read(KEYS[d.dataset.del]).filter(x=>x.id!==d.dataset.id));render();flash('Record deleted')}let r=e.target.closest('[data-receipt]');if(r){let p=read(KEYS.payments).find(x=>x.id===r.dataset.receipt);let w=window.open('','_blank');w.document.write(`<html><head><title>Receipt ${p.id}</title><style>body{font:16px Arial;max-width:700px;margin:50px auto;color:#193126}h1{color:#102d43;border-bottom:3px solid #d7ad55;padding-bottom:15px}table{width:100%;margin-top:30px}td{padding:12px;border-bottom:1px solid #ddd}</style></head><body><h1>DEEN AL NOOR TRAVELS</h1><p>Payment receipt: <b>${esc(p.id)}</b></p><table><tr><td>Client</td><td>${esc(p.client)}</td></tr><tr><td>Date</td><td>${fmt(p.date)}</td></tr><tr><td>Method</td><td>${esc(p.method)}</td></tr><tr><td>Reference</td><td>${esc(p.reference)||'—'}</td></tr><tr><td><b>Amount paid</b></td><td><b>${money(p.amount)}</b></td></tr></table><p style="margin-top:50px">Thank you for choosing Deen Al Noor Travels.</p><script>window.print()<\/script></body></html>`);w.document.close()}}}
seed();document.addEventListener('DOMContentLoaded',()=>{bind();render()});
